name: Markdown Lint & Spell Check

on:
  pull_request:
    branches: [main, master]
    paths:
      - '**.md'

jobs:
  lint-and-spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Runs Markdown Linting
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**.md'

      # Runs Spell Check
      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: '**.md'
          incremental_files_only: true
